#!/bin/bash
# Batch conversion script for all CALIPSO HDF files
# Generated by calipso_hdf_to_copc_conversion.ipynb

set -e  # Exit on error

echo "Starting batch conversion of CALIPSO HDF files to COPC"
echo "========================================================"

# Activate conda environment
source /opt/anaconda3/etc/profile.d/conda.sh
conda activate pdal

# Loop through all HDF files
for hdf_file in raw/*.hdf; do
    echo ""
    echo "Processing: $hdf_file"

    # Get base filename
    base=$(basename "$hdf_file" .hdf)

    # Define output paths
    las_file="converted_las/${base}.las"
    copc_file="final/${base}.copc.laz"

    # Step 1: HDF to LAS
    if [ ! -f "$las_file" ]; then
        echo "  Converting HDF to LAS..."
        python calipso_to_las.py "$hdf_file" "$las_file"
    else
        echo "  LAS file already exists, skipping."
    fi

    # Step 2: LAS to COPC
    if [ ! -f "$copc_file" ]; then
        echo "  Converting LAS to COPC..."

        # Create temporary pipeline with file paths
        cat las_to_copc_fixed.json |             sed "s|INPUT_LAS|$las_file|g" |             sed "s|OUTPUT_COPC|$copc_file|g" > temp_pipeline.json

        pdal pipeline temp_pipeline.json --verbose 4
        rm temp_pipeline.json
    else
        echo "  COPC file already exists, skipping."
    fi

    echo "  ✅ Complete: $copc_file"
done

echo ""
echo "========================================================"
echo "Batch conversion complete!"
echo "COPC files saved in: final/"
